name: ECR Push on Preview PR

on:
  #pull_request:
  #  types:
  #    - labeled
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: "define branch"
        default: 'feature/**'
permissions:
  id-token: write
  contents: read

jobs:
  ecr-push:
    runs-on: ubuntu-latest
    outputs:
        version: ${{ steps.version-generator.outputs.BUILD_NO }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::588531719611:role/ecr-push-image-github-actions
            aws-region: eu-central-1
    
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build staging image and push to ECR
          id: build-image
          uses: docker/build-push-action@v2
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: php-k8s
            IMAGE_TAG: k8s-pull-${{ github.sha }}
          with:
            context: .
            file: ./.docker/web/Dockerfile-k8s
            push: true
            build-args: |
              build_id=${{ github.sha }}
            tags: |
              ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
              ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            cache-to: type=inline