name: Add Label to PR

on:
  pull_request:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    env:
      PR_NO: ${{ github.event.pull_request.number }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add Label
      run: |
        gh pr edit $PR_NO --add-label 'preview'
